version: 2.1
orbs:
  node: circleci/node@5.3.0
  codecov: codecov/codecov@1.0.5
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn --frozen-lockfile
            - run: yarn run build
            - run: yarn add --dev jest-junit
            - run:
                command: yarn test -- --ci --runInBand --collectCoverage --reporters=default --reporters=jest-junit
                environment:
                  JEST_JUNIT_OUTPUT_DIR: "reports/junit/js-test-results.xml"
            - store_test_results:
                path: reports/junit
            - codecov/upload:
                file: coverage/coverage-final.json
  # release:
  #   branches:
  #     only: master
  #   steps:
  #     - checkout
  #     - node/with-cache:
  #         steps:
  #           - run: yarn install
  #           - run: yarn build
  #           - run: yarn run semantic-release

workflows:
    pipeline:
      jobs:
        - build-and-test
        # - release:
        #     requires:
        #       - build-and-test
