version: 2.1
orbs:
  node: circleci/node@1.1.6
  codecov: codecov/codecov@1.0.5
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn --frozen-lockfile
            - run: yarn test -- --collectCoverage
            - codecov/upload:
                file: coverage/
workflows:
    build-and-test:
      jobs:
        - build-and-test
